# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('composer', models.CharField(max_length=1000)),
                ('mood', models.CharField(max_length=1000)),
                ('that', models.CharField(max_length=1000)),
                ('samay', models.CharField(max_length=1000)),
                ('aroh', models.CharField(max_length=1000)),
                ('avaroh', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField()),
                ('entry_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_publish_date', models.DateTimeField(blank=True, null=True)),
                ('entry_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
