# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
