# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
